# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy
on:
  push:
    branches:
      - prodaction

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
              
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Firebase Deploy
      - uses: actions/checkout@v1
        with:
          args: deploy --only hosting:admin-nuft-kebop
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
